language: node_js
node_js:
  - "7"
  - "8"

before_install:
  - yarn global add typescript@2.3.4 typescript-formatter@5.2.0 tslint@5.4.3 mocha@3.2.0

script:
  - yarn test
  - tsfmt --verify $(find {src,test} -name "*.ts")
  - tslint -c tslint.json "src/**/*.ts"

matrix:
  fast_finish: true

branches:
  only:
    - master
